<?php
require __DIR__ . '/includes/bootstrap.php';
$meta = page_meta('About Us', 'Learn about J & S Constructions, a trusted Sri Lankan construction company building with quality and reliability since 1995.');
require __DIR__ . '/includes/header.php';
?>
<main>
<section class="page-hero py-24 text-white"><img src="<?= upload_url('library/project-luxury-villa.jpg') ?>" alt="About J & S Constructions"><div class="container-shell relative z-10"><span class="section-kicker !text-blue-300">About Us</span><h1 class="mt-5 max-w-4xl font-display text-5xl font-bold uppercase leading-tight sm:text-7xl">A Legacy Of Reliable Construction Since 1995</h1><p class="mt-6 max-w-2xl text-lg leading-8 text-slate-300">More than three decades of helping clients turn ideas, land and ambition into spaces made to last.</p></div></section>
<section class="py-24"><div class="container-shell grid items-center gap-14 lg:grid-cols-2"><div class="reveal"><img src="<?= asset('images/pages/about-cover.jpg') ?>" alt="J & S Constructions" class="aspect-[4/3] w-full rounded-[2rem] object-cover object-center shadow-2xl"></div><div class="reveal"><span class="section-kicker">Who We Are</span><h2 class="mt-5 font-display text-4xl font-bold uppercase text-brand-950 sm:text-5xl">Built On Experience. Driven By Quality.</h2><p class="mt-6 text-lg leading-8 text-slate-600">J & S Constructions is a trusted construction company delivering quality, reliable and efficient building solutions for residential, commercial and infrastructure projects.</p><p class="mt-4 leading-7 text-slate-600">Since 1995, our focus has remained consistent: understand the client clearly, plan every stage responsibly and execute each project with care. We value open communication, practical solutions and long-term relationships.</p><div class="mt-8 rounded-3xl border-l-4 border-brand-700 bg-brand-50 p-6 text-lg font-bold leading-8 text-brand-950">“Build your dream house with confidence, clarity and workmanship you can trust.”</div></div></div></section>
<section class="bg-slate-50 py-24"><div class="container-shell grid gap-7 lg:grid-cols-3"><?php foreach ([['target','Our Mission','To deliver dependable, high-quality construction solutions through responsible planning, skilled execution and honest communication.'],['eye','Our Vision','To be a trusted construction partner recognized for quality, reliability and lasting value across Sri Lanka.'],['gem','Our Promise','To treat every project with care, protect the client’s investment and build spaces that perform beautifully for years.']] as $item): ?><article class="card-lift reveal rounded-3xl border border-slate-200 bg-white p-8"><span class="grid h-14 w-14 place-items-center rounded-2xl bg-brand-50 text-brand-700"><i data-lucide="<?= e($item[0]) ?>"></i></span><h2 class="mt-6 font-display text-3xl font-bold uppercase text-brand-950"><?= e($item[1]) ?></h2><p class="mt-4 leading-7 text-slate-600"><?= e($item[2]) ?></p></article><?php endforeach; ?></div></section>
<section class="py-24"><div class="container-shell"><div class="mx-auto max-w-3xl text-center reveal"><span class="section-kicker">Core Values</span><h2 class="mt-5 font-display text-4xl font-bold uppercase text-brand-950 sm:text-5xl">The Standards Behind Every Project</h2></div><div class="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><?php foreach ([['shield-check','Integrity','Clear communication and honest guidance.'],['badge-check','Quality','Workmanship and materials chosen for lasting value.'],['clock-3','Reliability','Responsible scheduling and dependable coordination.'],['users','Client Focus','Solutions shaped around the client’s real needs.']] as $value): ?><div class="reveal rounded-3xl bg-brand-950 p-7 text-white"><i data-lucide="<?= e($value[0]) ?>" class="h-8 w-8 text-blue-300"></i><h3 class="mt-5 text-xl font-extrabold"><?= e($value[1]) ?></h3><p class="mt-2 text-sm leading-6 text-slate-300"><?= e($value[2]) ?></p></div><?php endforeach; ?></div></div></section>
<section class="container-shell"><div class="rounded-[2rem] bg-brand-50 px-7 py-12 text-center sm:px-12"><h2 class="font-display text-4xl font-bold uppercase text-brand-950">Planning A Construction Project?</h2><p class="mx-auto mt-4 max-w-2xl text-slate-600">Share your requirements with our team and take the first step toward a carefully planned build.</p><a href="<?= url('quotation.php') ?>" class="mt-7 inline-flex rounded-2xl bg-brand-700 px-7 py-4 font-extrabold text-white">Request a Quotation</a></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
