<?php
require __DIR__ . '/includes/bootstrap.php';
$meta=page_meta('Contact Us','Contact J & S Constructions by phone, email, WhatsApp or the website enquiry form.');
$errors=[];
if(is_post()){
 verify_csrf();$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$subject=trim($_POST['subject']??'');$message=trim($_POST['message']??'');
 if($name==='')$errors[]='Please enter your name.';if($phone===''&&$email==='')$errors[]='Please enter a phone number or email address.';if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Please enter a valid email address.';if($message==='')$errors[]='Please enter your message.';
 if(!$errors){$stmt=db()->prepare("INSERT INTO contact_messages(name,email,phone,subject,message,status,created_at) VALUES(?,?,?,?,?,'New',NOW())");$stmt->execute([$name,$email,$phone,$subject,$message]);flash('success','Your message has been sent successfully.');redirect('contact.php');}
}
require __DIR__ . '/includes/header.php';
?>
<main>
<section class="page-hero py-24 text-white"><img src="<?= upload_url('library/project-office-interior.jpg') ?>" alt="Contact J & S Constructions"><div class="container-shell relative z-10"><span class="section-kicker !text-blue-300">Contact Us</span><h1 class="mt-5 font-display text-5xl font-bold uppercase sm:text-7xl">Let’s Discuss Your Next Build</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Reach us directly or send a message using the form below.</p></div></section>
<section class="py-20"><div class="container-shell grid gap-12 lg:grid-cols-[380px_minmax(0,1fr)]"><aside class="grid content-start gap-5"><?php foreach([['phone','Call Us',setting('phone_1','075 089 6076').' / '.setting('phone_2','077 077 0671')],['mail','Email Us',setting('email','jsconstructions@gmail.com')],['globe','Website',setting('website','jsconstructions.lk')],['map-pin','Location',setting('address','Sri Lanka')]] as $item): ?><div class="rounded-3xl border border-slate-200 bg-white p-6"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-700"><i data-lucide="<?= e($item[0]) ?>"></i></span><h2 class="mt-4 text-lg font-extrabold text-brand-950"><?= e($item[1]) ?></h2><p class="mt-1 break-words text-slate-600"><?= e($item[2]) ?></p></div><?php endforeach; ?><div class="contact-visual-card"><img src="<?= upload_url('library/project-premium-office-interior.jpg') ?>" alt="Professional consultation and construction planning"><div class="visual-badge"><h3>Visit, Call or WhatsApp Us</h3><p>We are ready to guide you from the initial discussion to the next practical step of your project.</p></div></div></aside><div class="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/40 sm:p-10"><h2 class="font-display text-4xl font-bold uppercase text-brand-950">Send A Message</h2><p class="mt-3 text-slate-600">We will reply using the contact details you provide.</p><?php if($errors): ?><div class="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800"><?php foreach($errors as $error): ?><p><?= e($error) ?></p><?php endforeach; ?></div><?php endif; ?><form method="post" class="mt-7 grid gap-5 sm:grid-cols-2"><?= csrf_field() ?><label class="grid gap-2 text-sm font-bold">Full Name *<input class="form-input" name="name" value="<?= e(old('name')) ?>" required></label><label class="grid gap-2 text-sm font-bold">Phone Number<input class="form-input" name="phone" value="<?= e(old('phone')) ?>"></label><label class="grid gap-2 text-sm font-bold">Email Address<input type="email" class="form-input" name="email" value="<?= e(old('email')) ?>"></label><label class="grid gap-2 text-sm font-bold">Subject<input class="form-input" name="subject" value="<?= e(old('subject')) ?>"></label><label class="grid gap-2 text-sm font-bold sm:col-span-2">Message *<textarea class="form-input min-h-44" name="message" required><?= e(old('message')) ?></textarea></label><button class="rounded-2xl bg-brand-700 px-7 py-4 font-extrabold text-white sm:col-span-2">Send Message</button></form></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
