<?php
require __DIR__ . '/includes/auth.php';
$adminTitle='Admin Profile';$errors=[];$user=admin_user();$stmt=db()->prepare('SELECT * FROM admins WHERE id=?');$stmt->execute([$user['id']]);$record=$stmt->fetch();
if(is_post()){
 verify_csrf();$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$current=$_POST['current_password']??'';$new=$_POST['new_password']??'';$confirm=$_POST['confirm_password']??'';
 if($name==='')$errors[]='Name is required.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='A valid email is required.';
 $password=$record['password'];if($new!==''){if(!password_verify($current,$record['password']))$errors[]='Current password is incorrect.';if(strlen($new)<10)$errors[]='New password must contain at least 10 characters.';if($new!==$confirm)$errors[]='New password confirmation does not match.';if(!$errors)$password=password_hash($new,PASSWORD_DEFAULT);}
 if(!$errors){try{$stmt=db()->prepare('UPDATE admins SET name=?,email=?,password=? WHERE id=?');$stmt->execute([$name,$email,$password,$record['id']]);$_SESSION['admin_user']=['id'=>(int)$record['id'],'name'=>$name,'email'=>$email];flash('success','Admin profile updated.');redirect('admin/profile.php');}catch(PDOException){$errors[]='That email address is already in use.';}}
}
require __DIR__ . '/includes/header.php';
?>
<section class="admin-card max-w-2xl p-6 sm:p-8"><h2 class="font-display text-3xl font-bold uppercase text-brand-950">Profile & Password</h2><p class="mt-2 text-slate-500">Update the administrator name, login email or password.</p><?php if($errors): ?><div class="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700"><?= e(implode(' ',$errors)) ?></div><?php endif; ?><form method="post" class="mt-8 grid gap-5"><?= csrf_field() ?><label class="grid gap-2 text-sm font-bold">Admin Name<input class="form-input" name="name" value="<?= e($_POST['name']??$record['name']) ?>" required></label><label class="grid gap-2 text-sm font-bold">Login Email<input type="email" class="form-input" name="email" value="<?= e($_POST['email']??$record['email']) ?>" required></label><div class="mt-3 border-t border-slate-100 pt-6"><h3 class="font-extrabold text-brand-950">Change Password</h3><p class="mt-1 text-xs text-slate-400">Leave these fields empty to keep the current password.</p></div><label class="grid gap-2 text-sm font-bold">Current Password<input type="password" class="form-input" name="current_password"></label><label class="grid gap-2 text-sm font-bold">New Password<input type="password" class="form-input" name="new_password"></label><label class="grid gap-2 text-sm font-bold">Confirm New Password<input type="password" class="form-input" name="confirm_password"></label><button class="rounded-xl bg-brand-700 px-7 py-4 font-extrabold text-white">Update Profile</button></form></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
